# Generated by Django 3.2.23 on 2023-12-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='post',
            name='review',
        ),
        migrations.RemoveField(
            model_name='post',
            name='review_count',
        ),
    ]
