# Generated by Django 3.2.23 on 2023-12-01 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20231201_1401'),
        ('posts', '0004_auto_20231201_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ratings.rating'),
            preserve_default=False,
        ),
    ]
