# Generated by Django 3.2.23 on 2023-12-01 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
    ]
