# Generated by Django 3.2.23 on 2023-12-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='average_rating',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
