# Generated by Django 3.2.23 on 2023-12-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
