# Generated by Django 3.2.23 on 2023-12-08 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20231202_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avg_rating',
        ),
        migrations.RemoveField(
            model_name='post',
            name='number_rating',
        ),
    ]
