# Generated by Django 3.2.23 on 2023-11-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='homepage',
            field=models.URLField(blank=True),
        ),
    ]
