# Generated by Django 3.2.23 on 2023-11-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='homepage',
            field=models.TextField(blank=True),
        ),
    ]
