# Generated by Django 3.2.23 on 2023-12-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_alter_rating_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='post',
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2 '), (3, '3 '), (4, '4 '), (5, '5')], default=0),
        ),
    ]
