# Generated by Django 3.2.23 on 2023-12-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_average_rating'),
        ('ratings', '0003_auto_20231201_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='posts.post'),
        ),
    ]
