# Generated by Django 3.2.23 on 2023-12-02 11:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_remove_post_average_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ratings', '0004_rating_post'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('owner', 'post')},
        ),
    ]
