# Generated by Django 3.2.23 on 2023-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='content',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='question',
            field=models.CharField(choices=[('LOGIN', 'Trouble logging in'), ('PASSWORD', 'Forgotten password'), ('REPORT', 'Report inappropriate site content'), ('OTHER', 'Other reason')], max_length=50),
        ),
    ]
