# Generated by Django 3.2.23 on 2023-12-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20231210_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='question',
            field=models.CharField(max_length=50),
        ),
    ]
