# Generated by Django 3.2.23 on 2023-12-08 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231208_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review_user',
            new_name='owner',
        ),
    ]
